import {
  Utensils,
  UtensilsCrossed,
  Coffee,
  Cookie,
  IceCream,
  CupSoda,
  Store,
  Pill,
  Droplets,
  Bike,
  Car,
  Truck,
  Disc,
  Droplet,
  BatteryCharging,
  Landmark,
  Smartphone,
  Package,
  Warehouse,
  Bath,
  BedDouble,
  SquareParking,
  ShowerHead,
  type LucideIcon,
} from "lucide-react";

export const FORMAT_ICONS: Record<string, LucideIcon> = {
  "A1.1": Utensils,
  "A1.2": UtensilsCrossed,
  "A1.3": Coffee,
  "A1.4": Cookie,
  "A1.5": IceCream,
  "A1.6": CupSoda,
  "A2.1": Store,
  "A2.2": Pill,
  "A3.1": Droplets,
  "A3.2": Bike,
  "A3.3": Car,
  "A3.4": Truck,
  "A3.5": Disc,
  "A3.6": Droplet,
  "A3.7": BatteryCharging,
  "A4.1": Landmark,
  "A4.2": Smartphone,
  "A5.1": Package,
  "A5.2": Warehouse,
  "A6.1": Bath,
  "A6.2": BedDouble,
  "A7.1": SquareParking,
  "A7.2": ShowerHead,
};
